### ISSUE TITLE
ERROR: could not decompile PDB because it does not contain a string table: StreamNameNotFound

### ISSUE THREAD

**Issue by x-0D** [camden-smallwood/pdb-decompiler#14]
using official Microsoft pdb file for mmc.exe [link](http://msdl.microsoft.com/download/symbols/mmc.pdb/D2D53FA23F71D6C8D90B6B9B4ADB6A101/mmc.pdb)
Running in Github CodeSpaces
![image](https://user-images.githubusercontent.com/87000516/207066450-4e4ea38d-1900-40dd-86af-e37c43ac1a0d.png)

mmc.pdb (notepad++ opened)
![image](https://user-images.githubusercontent.com/87000516/207067041-c3592484-33c9-4ae3-8a7d-3875461444be.png)

**Comment by camden-smallwood** [comment]
Hello, as the error message states, the PDB file does not contain a string table. Is there a place this PDB file can be downloaded? If so, I can take a look and see if there are any workarounds. If not, the only thing I can say is that this is expected behavior, because a string table is required to decompile.

**Comment by x-0D** [comment]
Thank you, i'll waiting for your answer

**Comment by camden-smallwood** [comment]
So after spending a day attempting to find a workaround, I've determined that due to the lack of a string table (missing the `/names` stream), this .PDB file is essentially just a symbol map and cannot be decompiled. To be sure, I dumped the file using the `cvdump` utility and found that there is no source line information, no embedded types, and all of the functions have a `NONE` return type, which means this PDB has been effectively stripped. The most it could be used for is labeling functions when debugging or reverse-engineering the `mmc.exe` binary. I've included the text dump for reference. Sorry, I tried.

[mmc_pdb_dump.txt](https://github.com/camden-smallwood/pdb-decompiler/files/10221144/mmc_pdb_dump.txt)

![image](https://user-images.githubusercontent.com/52939755/207417428-07410e76-001d-4802-a5a9-0ae3e95a541b.png)
